### ISSUE TITLE
Писмьо "Спасибо за регистрацию"

### ISSUE THREAD

**Issue by Feodoros** [MyMeetAI/mymeet.ai#1]
При регистрации юзера ему приходит на почту письмо:
- спс за регистрацию
- дарим 3 бесплатные встречи
- реклама подписки ПРО
- скидка до 30 авг

**Comment by Feodoros** [comment]
https://www.figma.com/file/Ma7dtZb6eSHJ5YoaiVEUn2/AppMyMeet?node-id=401%3A947&mode=dev

**Comment by Feodoros** [comment]
если что теперь изображения загружаем в хорошем качестве (при экспорте ставим 2Х или больше и пнг) на гит в наш публичный реп https://github.com/MyMeetAI/mymeet.ai и в письме при верстке ставим ссылку до изображения

**Comment by VetDeveloper** [comment]
Скрины

Гугл десктоп

![image](https://github.com/MyMeetAI/mymeet.ai/assets/101522315/dadcb3e1-af77-4a4b-b61c-b0c448f4e986)

Меил ру десктоп

![image](https://github.com/MyMeetAI/mymeet.ai/assets/101522315/dd198c02-61a5-442f-8dd3-7eb209bcdbf2)

Гугл телефон

![image](https://github.com/MyMeetAI/mymeet.ai/assets/101522315/162904ad-d8d0-4eda-bd27-1d3321ce8432)

Меил ру телефон

![image](https://github.com/MyMeetAI/mymeet.ai/assets/101522315/f594a94f-0894-4af2-b6bc-100ac4cb38f7)

**Comment by Feodoros** [comment]
Мне кажется или шрифт немного другой?


![Image](https://github.com/MyMeetAI/mymeet.ai/assets/23313519/8145fa3c-e657-41ba-b182-8d0882d675d2)



![Image](https://github.com/MyMeetAI/mymeet.ai/assets/23313519/257a13b6-c84a-45ef-b0e4-f8bfd92abf9e)

**Comment by VetDeveloper** [comment]
> Мне кажется или шрифт немного другой?
> 
> ![Image](https://user-images.githubusercontent.com/23313519/259891782-8145fa3c-e657-41ba-b182-8d0882d675d2.png)
> 
> ![Image](https://user-images.githubusercontent.com/23313519/259891807-257a13b6-c84a-45ef-b0e4-f8bfd92abf9e.png)

Там просто надпись сделана картинкой. Шрифт подобрать не могу. Я сказал картинку, но тогда цвет не адаптируется на черной теме и название так и остается черным

![image](https://github.com/MyMeetAI/mymeet.ai/assets/101522315/5028c472-bc60-45ec-aeaa-bca82c925407)

**Comment by VetDeveloper** [comment]
Попробовал решить через медиа запросы, но gmail не поддерживает медиа запрос на тему

**Comment by Feodoros** [comment]
А если вот так лого задавать, как в первом письме?
```
<table class="preview" style="margin: 0 auto;">
                <tr>
                    <td>
                        <img id="preview" style="width: 28px; height: 32px; vertical-align: middle;" src="https://raw.githubusercontent.com/MyMeetAI/mymeet.ai/main/logo.png"></img>
                    </td>
                    <td>
                        <a href="https://mymeet.ai" style="text-decoration:none"><h1 id="heading"
                            style="padding-left: 5px; color: #000000; font-size: 30px; font-weight: 600; width: auto; font-family:Verdana; margin: 0;">
                            MyMeet.ai</h1></a>
                    </td>
                </tr>                
            </table>
```

**Comment by VetDeveloper** [comment]
> А если вот так лого задавать, как в первом письме?
> 
> ```
> <table class="preview" style="margin: 0 auto;">
>                 <tr>
>                     <td>
>                         <img id="preview" style="width: 28px; height: 32px; vertical-align: middle;" src="https://raw.githubusercontent.com/MyMeetAI/mymeet.ai/main/logo.png"></img>
>                     </td>
>                     <td>
>                         <a href="https://mymeet.ai" style="text-decoration:none"><h1 id="heading"
>                             style="padding-left: 5px; color: #000000; font-size: 30px; font-weight: 600; width: auto; font-family:Verdana; margin: 0;">
>                             MyMeet.ai</h1></a>
>                     </td>
>                 </tr>                
>             </table>
> ```

Как ты подметил, тогда шрифт отличается от дизайна. В дизайне используется шрифт, который не поддерживается многими сервисами почт. В этом и загвоздка. Я хотел картинку вставить, она не адаптируется.. Инверсию цвета сделал для текста, запихнул две картинки и подрубил медиа запрос на тему: при темной теме отображается лишь светлый текст, при светлой теме - темный; но gmail не поддерживает запрос на тему.. Поэтому я пока вижу три варианта: юзать картинку с темным текстом, юзать текст с другим шрифтом, юзать другой шрифт в дизайне.

**Comment by VetDeveloper** [comment]
В дизайне юзается `unbounded` (небезопасный для email) шрифт, а там, где ты скинул, `Verdana` (безопасный для email)

**Comment by Feodoros** [comment]
Да, я помню, что там не все поддерживаются. Ничего страшного если будет отличаться немного от дизайна. Мы с Ваней решили, что Verdana норм. Давай везде этот шрифт использовать и лого делать текстом, чтобы была инверсия.

**Comment by Feodoros** [comment]
И аналогично шрифт поменять во втором письме тоже на Verdana. И в следующих письмах тоже его будем исспользовать.

**Comment by VetDeveloper** [comment]
Шрифт везде используется `Verdana`

**Google desk**

![image](https://github.com/MyMeetAI/mymeet.ai/assets/101522315/33cbce53-9a2e-4896-af7e-010f7ca9808c)

**Mail.ru desk**

![image](https://github.com/MyMeetAI/mymeet.ai/assets/101522315/ca2e647a-e1a1-4bb1-8deb-4640dbdb48ea)

**Google mobile**

![image](https://github.com/MyMeetAI/mymeet.ai/assets/101522315/52fef98b-59c9-4d27-97ed-3d7fa368f5be)

**Mail.ru mobile**

![image](https://github.com/MyMeetAI/mymeet.ai/assets/101522315/e757284f-f531-4340-b5a2-2b84f0a69e0d)
