### ISSUE TITLE
Письмо "Спасибо за подписку"

### ISSUE THREAD

**Issue by Feodoros** [MyMeetAI/mymeet.ai#2]
После покупки подписки ПРО благодарим юзера за подписку

**Comment by Feodoros** [comment]
https://www.figma.com/file/Ma7dtZb6eSHJ5YoaiVEUn2/AppMyMeet?node-id=401%3A947&mode=dev

**Comment by Feodoros** [comment]
если что теперь изображения загружаем в хорошем качестве (при экспорте ставим 2Х и пнг) на гит в наш публичный реп https://github.com/MyMeetAI/mymeet.ai и в письме при верстке ставим ссылку до изображения

**Comment by VetDeveloper** [comment]
Взял таску

**Comment by VetDeveloper** [comment]
Прикрепляю html файлы с версткой писем
[thanks_for_promo.zip](https://github.com/MyMeetAI/mymeet.ai/files/12311644/thanks_for_promo.zip)

**Comment by VetDeveloper** [comment]
Скрины.

Гугл с телефона

![image](https://github.com/MyMeetAI/mymeet.ai/assets/101522315/6dc04b56-5599-463d-a130-a09a4c12956c)

Меил ру с телефона

![image](https://github.com/MyMeetAI/mymeet.ai/assets/101522315/0fa60891-395d-4924-8448-3aa763f713c0)

Гугл с компа

![image](https://github.com/MyMeetAI/mymeet.ai/assets/101522315/82f6077d-20c4-4065-b638-d93f0381c9fb)

Меил ру с компа

![image](https://github.com/MyMeetAI/mymeet.ai/assets/101522315/7e5f5cd2-b9f6-4d04-bdb9-a225639f4ed4)

**Comment by Feodoros** [comment]
Кажется или с компа шрифт другой?

![Image](https://github.com/MyMeetAI/mymeet.ai/assets/23313519/c413f8b0-14ab-429d-b4ba-4ee8ad2b8f2c)



![Image](https://github.com/MyMeetAI/mymeet.ai/assets/23313519/9957e2ee-7388-46d7-987f-253a74f51949)

**Comment by VetDeveloper** [comment]
> Кажется или с компа шрифт другой?
> 
> ![Image](https://user-images.githubusercontent.com/23313519/259891971-c413f8b0-14ab-429d-b4ba-4ee8ad2b8f2c.png)
> 
> ![Image](https://user-images.githubusercontent.com/23313519/259891987-9957e2ee-7388-46d7-987f-253a74f51949.png)

блин, мб, скрин на компе до фикса шрифтов. Я потом подметил и пофиксил. Сейчас на компе всё норм

![image](https://github.com/MyMeetAI/mymeet.ai/assets/101522315/53569d2c-286b-4fcb-93ce-3d998dd0f8e9)
